version: "3"
services:
  api:
    container_name: api
    build: .
    command: bash -c 'mix ecto.setup && mix phx.server'
    volumes:
      - .:/opt/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: kartoza/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atlas_prod
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
